spring:
  couchbase:
    bootstrap-hosts: "127.0.0.1"
    bucket:
      name: "intentmodeling"
      password: "123456"
  data:
    couchbase:
      auto-index: true

    mongodb:
      host: "10.2.40.44"
      database: "qa_robot"